name: one_thousand_and_one_designs
description: "1001 Designs"

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  zoomable_interactive_viewer: any
  flutter_bloc: ^9.0.0
  go_router: ^14.7.1
  flutter_web_plugins:
    sdk: flutter
  get_it: ^8.0.3
  copy_with_extension: ^6.0.1
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  copy_with_extension_gen: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/